### ISSUE TITLE
Lime test html5 -debug problem

### ISSUE THREAD

**Issue by ghost** [AngelDTF/FNF-NewgroundsPort#9] opened 2022-01-14 10:06 UTC
i recive this error when i try to port html5 test -debug

source/Controls.hx:480: characters 5-37 : Cannot access field or identifier inputID for writing
source/Controls.hx:490: characters 5-37 : Cannot access field or identifier inputID for writing
source/TitleState.hx:118: characters 3-8 : Unknown identifier : video
source/TitleState.hx:119: characters 3-8 : Unknown identifier : video
source/TitleState.hx:120: characters 3-8 : Unknown identifier : video
source/TitleState.hx:139: characters 3-12 : Unknown identifier : netStream
source/TitleState.hx:140: characters 3-12 : Unknown identifier : netStream
source/TitleState.hx:141: characters 33-40 : Unknown identifier : overlay
source/TitleState.hx:141: characters 33-40 : ... For function argument 'child'

**Comment by AngelWyvern** [comment] 2022-01-14 16:59
Duplicate of [issue #7](https://github.com/AngelDTF/FNF-NewgroundsPort/issues/7).
Read [my comment](https://github.com/AngelDTF/FNF-NewgroundsPort/issues/7#issuecomment-1001010985) on that issue for further information.

**Comment by ghost** [comment] 2022-01-19 19:57
ok

**Comment by AngelWyvern** [comment] 2022-01-20 22:40
Fixed in commit 1d5f0f0e711ff9bf7cee3796babb681a2de451f8

**Closed as completed by AngelWyvern** 2022-01-20 22:40 UTC
Labels: bug, duplicate
