### ISSUE TITLE
Bug Report: Notes move choppy

### ISSUE THREAD

**Issue by FNFFAN737** [AngelDTF/FNF-NewgroundsPort#25] opened 2022-05-21 23:50 UTC
While playing on the remastered version, i noticed that the notes move across the screen noticeably pretty choppy, especially compared to 0.2.8 and even your own legacy branch. I’m not exactly sure where in source this issue would be located.

**Comment by Trayfellow** [comment] 2022-05-25 11:44
got this same issue too, but the screenshot i posted fixes it being choppy for some reason
![image](https://user-images.githubusercontent.com/48515908/170254357-d7213cf6-6582-4b79-b4ea-16a0fd40e856.png)

**Comment by AngelWyvern** [comment] 2022-05-25 17:22
_Apologies for the late response, I've been in bed with Covid for almost a week._

This is an issue caused by a change in the v0.2.8 PlayState update script, where Ninjamuffin (for some reason) decided to use the (more accurate although choppier) sound time rather than incrementing the variable based on how much time has elapsed (smoother).

There's a possibility that this may just be a preprocessor conditional for web targets (since sound works different on browsers), but I would have to check through some coding VODs to be sure, since preprocessor conditionals don't show in the compiled JS code.

**Comment by Trayfellow** [comment] 2022-05-25 21:16
> _Apologies for the late response, I've been in bed with Covid for almost a week._
> 
> This is an issue caused by a change in the v0.2.8 PlayState update script, where Ninjamuffin (for some reason) decided to use the (more accurate although choppier) sound time rather than incrementing the variable based on how much time has elapsed (smoother).
> 
> There's a possibility that this may just be a preprocessor conditional for web targets (since sound works different on browsers), but I would have to check through some coding VODs to be sure, since preprocessor conditionals don't show in the compiled JS code.

get well soon

**Comment by AngelWyvern** [comment] 2022-06-14 16:31
I've been searching for any VODs to see if I can prove my theory true, however I am unable to find any clips around the time of v0.2.8's development showing that specific section in `PlayState.hx`. I'm gonna close this issue for now, but if you can find any VODs relating to this, feel free to reopen this issue.

**Closed as completed by AngelWyvern** 2022-06-14 16:31 UTC
Labels: bug

**Comment by RagdollClash** [comment] 2022-12-16 10:03
Might be worth mentioning that the [SiIvaGunner Ugh rip](https://youtu.be/c_6rt9Tj5aI) has these same stuttering notes, more evident by going frame-by-frame.

https://user-images.githubusercontent.com/15317421/208073848-111893e9-58b5-4fb8-85dc-d3e0fee5bb89.mp4

**Comment by Trayfellow** [comment] 2022-12-16 12:03
> Might be worth mentioning that the [SiIvaGunner Ugh rip](https://youtu.be/c_6rt9Tj5aI) has these same stuttering notes, more evident by going frame-by-frame.
> 
>  2022-12-16_02-01-41_vivaldi.mp4

if i was playing fnf at 144fps and the notes were choppy i wouldnt let that slide lol
