### ISSUE TITLE
Bug Report: this.

### ISSUE THREAD

**Issue by DeceptedPar** [AngelDTF/FNF-NewgroundsPort#7] opened 2021-12-22 14:07 UTC
![image](https://user-images.githubusercontent.com/64243677/147105227-617cca9e-1100-46c8-9613-e4031cabe49c.png)
all I did was try to compile this

**Comment by AngelWyvern** [comment] 2021-12-25 12:22
(Apologies for the slow response, I don’t have a stable internet connection at the moment.)

The repository is still a heavy WIP, and not all features are finished right now. My laptop doesn’t have an internet connection at the moment, so there are some changes that have yet to be uploaded. You can manually comment out these lines for now, but please know that not everything will work as intended for a little bit (e.g. options, week 7, etc.).

**Comment by AngelWyvern** [comment] 2022-01-20 22:40
Fixed in commit 1d5f0f0e711ff9bf7cee3796babb681a2de451f8

**Closed as completed by AngelWyvern** 2022-01-20 22:40 UTC
Labels: bug, in progress
